ag9032v1/scripts/ag9032v1_platform_fancontrol.service lib/systemd/system
ag9032v1/scripts/ag9032v1_platform_led.service lib/systemd/system
ag9032v1/scripts/ag9032v1_platform_modules.service lib/systemd/system
ag9032v1/scripts/ag9032v1_platform_modules.sh usr/local/bin
ag9032v1/scripts/led_status.sh usr/local/bin
ag9032v1/sonic_platform-1.0-py3-none-any.whl usr/share/sonic/device/x86_64-delta_ag9032v1-r0